-- What the public demo (Streamlit Community Cloud) may do, as role PDM_PUBLIC_DEMO.
-- Read the dashboards, create work orders through the guarded procedure, chat with the agent.
-- It cannot call RESET_DEMO_DATA, change objects, or read anything outside PDM_DB.
-- Run by deploy/setup_public_demo.sql and after every deploy (scripts recreate objects, dropping grants).
-- Runs as PDM_DEPLOYER, which owns the objects.

GRANT USAGE ON DATABASE PDM_DB TO ROLE PDM_PUBLIC_DEMO;
GRANT USAGE ON SCHEMA PDM_DB.RAW TO ROLE PDM_PUBLIC_DEMO;
GRANT USAGE ON SCHEMA PDM_DB.CURATED TO ROLE PDM_PUBLIC_DEMO;
GRANT USAGE ON SCHEMA PDM_DB.ML TO ROLE PDM_PUBLIC_DEMO;
GRANT USAGE ON SCHEMA PDM_DB.APP TO ROLE PDM_PUBLIC_DEMO;

GRANT SELECT ON ALL TABLES IN DATABASE PDM_DB TO ROLE PDM_PUBLIC_DEMO;
GRANT SELECT ON ALL VIEWS IN DATABASE PDM_DB TO ROLE PDM_PUBLIC_DEMO;
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE PDM_DB TO ROLE PDM_PUBLIC_DEMO;
-- The evaluation answer key stays private; the app reads only ML.MODEL_EVALUATION.
REVOKE SELECT ON TABLE PDM_DB.ML.SYNTH_GROUND_TRUTH FROM ROLE PDM_PUBLIC_DEMO;

-- Work-order form and agent tool (both EXECUTE AS OWNER, with guardrails)
GRANT USAGE ON PROCEDURE PDM_DB.APP.CREATE_WORK_ORDER(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE PDM_PUBLIC_DEMO;
GRANT USAGE ON PROCEDURE PDM_DB.APP.CREATE_WORK_ORDER_TOOL(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE PDM_PUBLIC_DEMO;

-- Agent chat
GRANT USAGE ON AGENT PDM_DB.APP.PDM_AGENT TO ROLE PDM_PUBLIC_DEMO;
GRANT SELECT ON SEMANTIC VIEW PDM_DB.APP.PDM_SEMANTIC_VIEW TO ROLE PDM_PUBLIC_DEMO;
GRANT USAGE ON CORTEX SEARCH SERVICE PDM_DB.APP.INSPECTION_SEARCH TO ROLE PDM_PUBLIC_DEMO;
