-- 02: raw tables (IT = ERP/maintenance, OT = sensors/power/controllers)
-- WARNING: CREATE OR REPLACE drops existing data. Run 03_synthetic_data.sql afterwards.

-- ERP / master data
CREATE OR REPLACE TABLE PDM_DB.RAW.PLANTS (
  PLANT_ID VARCHAR PRIMARY KEY, PLANT_NAME VARCHAR, CITY VARCHAR, COUNTRY VARCHAR,
  CLIMATE_ZONE VARCHAR COMMENT 'HUMID, DRY, TEMPERATE - affects moisture risk', TIMEZONE VARCHAR);

CREATE OR REPLACE TABLE PDM_DB.RAW.PRODUCTION_LINES (
  LINE_ID VARCHAR PRIMARY KEY, PLANT_ID VARCHAR REFERENCES PDM_DB.RAW.PLANTS(PLANT_ID),
  LINE_NAME VARCHAR, POWER_FEED_ID VARCHAR COMMENT 'Shared power feed - common-cause risk',
  HAS_UPS BOOLEAN, HAS_SURGE_PROTECTION BOOLEAN);

CREATE OR REPLACE TABLE PDM_DB.RAW.MACHINES (
  MACHINE_ID VARCHAR PRIMARY KEY, LINE_ID VARCHAR REFERENCES PDM_DB.RAW.PRODUCTION_LINES(LINE_ID),
  MACHINE_NAME VARCHAR, MACHINE_TYPE VARCHAR COMMENT 'PUMP, PRESS, MIXER, CONVEYOR, COMPRESSOR',
  MANUFACTURER VARCHAR, MODEL VARCHAR, INSTALL_DATE DATE, RATED_RPM NUMBER, RATED_CURRENT_AMPS NUMBER(8,2),
  IDEAL_CYCLE_TIME_SEC NUMBER(8,2) COMMENT 'For OEE performance', CRITICALITY VARCHAR COMMENT 'A, B, C');

CREATE OR REPLACE TABLE PDM_DB.RAW.COMPONENTS (
  COMPONENT_ID VARCHAR PRIMARY KEY, MACHINE_ID VARCHAR REFERENCES PDM_DB.RAW.MACHINES(MACHINE_ID),
  COMPONENT_TYPE VARCHAR COMMENT 'BEARING, MOTOR, DRIVE, PLC, PSU, RAID_DISK, CONTROL_BOARD, NETWORK_SWITCH, CABLE',
  REDUNDANCY_GROUP VARCHAR COMMENT 'e.g. PSU pair; NULL if not redundant', PART_NUMBER VARCHAR,
  INSTALL_DATE DATE, EXPECTED_MTBF_HOURS NUMBER);

CREATE OR REPLACE TABLE PDM_DB.RAW.SPARE_PARTS (
  PART_NUMBER VARCHAR, PART_NAME VARCHAR, COMPONENT_TYPE VARCHAR,
  UNIT_COST_USD NUMBER(10,2), LEAD_TIME_DAYS NUMBER, QTY_ON_HAND NUMBER, REORDER_POINT NUMBER, PLANT_ID VARCHAR,
  PRIMARY KEY (PART_NUMBER, PLANT_ID));

-- OT: machine sensors (every 5 min)
CREATE OR REPLACE TABLE PDM_DB.RAW.SENSOR_READINGS (
  MACHINE_ID VARCHAR, READING_TS TIMESTAMP_NTZ,
  VIBRATION_MM_S FLOAT, BEARING_TEMP_C FLOAT, MOTOR_WINDING_TEMP_C FLOAT, RPM FLOAT,
  CURRENT_L1_A FLOAT, CURRENT_L2_A FLOAT, CURRENT_L3_A FLOAT, LOAD_PCT FLOAT,
  CABINET_HUMIDITY_PCT FLOAT, CABINET_TEMP_C FLOAT, DEW_POINT_C FLOAT, LEAK_DETECTED BOOLEAN,
  INSULATION_RESISTANCE_MOHM FLOAT, TERMINAL_TEMP_C FLOAT, CONTACT_RESISTANCE_MOHM FLOAT, DC_RIPPLE_MV FLOAT);

-- OT: line power quality (every 5 min) + discrete events
CREATE OR REPLACE TABLE PDM_DB.RAW.POWER_READINGS (
  POWER_FEED_ID VARCHAR, READING_TS TIMESTAMP_NTZ,
  VOLTAGE_L1_V FLOAT, VOLTAGE_L2_V FLOAT, VOLTAGE_L3_V FLOAT, FREQUENCY_HZ FLOAT, THD_PCT FLOAT);

CREATE OR REPLACE TABLE PDM_DB.RAW.POWER_EVENTS (
  EVENT_ID VARCHAR PRIMARY KEY, POWER_FEED_ID VARCHAR, EVENT_TS TIMESTAMP_NTZ,
  EVENT_TYPE VARCHAR COMMENT 'OUTAGE, SAG, SURGE, TRANSIENT_SPIKE, RESTART_INRUSH, GROUND_FAULT, PHASE_LOSS, ESD',
  DURATION_MS NUMBER, MAGNITUDE FLOAT COMMENT 'Peak V or % of nominal', SURGE_PROTECTOR_TRIGGERED BOOLEAN);

-- OT: redundant component status
CREATE OR REPLACE TABLE PDM_DB.RAW.COMPONENT_HEALTH (
  COMPONENT_ID VARCHAR, STATUS_TS TIMESTAMP_NTZ,
  STATUS VARCHAR COMMENT 'HEALTHY, DEGRADED, REBUILDING, FAILED', DETAIL VARCHAR);

-- IT/OT: controller and edge PC utilization
CREATE OR REPLACE TABLE PDM_DB.RAW.SYSTEM_METRICS (
  MACHINE_ID VARCHAR, READING_TS TIMESTAMP_NTZ, DEVICE VARCHAR COMMENT 'PLC, HMI, EDGE_PC',
  CPU_PCT FLOAT, MEMORY_PCT FLOAT, DISK_PCT FLOAT, NETWORK_ERRORS NUMBER, WATCHDOG_RESETS NUMBER);

-- Controller / drive fault codes
CREATE OR REPLACE TABLE PDM_DB.RAW.FAULT_LOGS (
  MACHINE_ID VARCHAR, FAULT_TS TIMESTAMP_NTZ, SOURCE VARCHAR COMMENT 'DRIVE, PLC, PSU, BREAKER',
  FAULT_CODE VARCHAR, FAULT_DESCRIPTION VARCHAR, SEVERITY VARCHAR);

-- Maintenance
CREATE OR REPLACE TABLE PDM_DB.RAW.FAILURES (
  FAILURE_ID VARCHAR PRIMARY KEY, MACHINE_ID VARCHAR, COMPONENT_ID VARCHAR,
  FAILURE_TS TIMESTAMP_NTZ, RESTORED_TS TIMESTAMP_NTZ,
  FAILURE_MODE VARCHAR COMMENT 'MECHANICAL, MOISTURE, POWER_QUALITY, POWER_SHOCK, WIRING, REDUNDANCY_LOSS, OVERLOAD, RANDOM',
  ROOT_CAUSE VARCHAR, DOWNTIME_MINUTES NUMBER);

CREATE OR REPLACE TABLE PDM_DB.RAW.WORK_ORDERS (
  WORK_ORDER_ID VARCHAR PRIMARY KEY, MACHINE_ID VARCHAR, COMPONENT_ID VARCHAR, FAILURE_ID VARCHAR,
  WO_TYPE VARCHAR COMMENT 'CORRECTIVE, PREVENTIVE, PREDICTIVE, INSPECTION', PRIORITY VARCHAR,
  STATUS VARCHAR COMMENT 'OPEN, IN_PROGRESS, COMPLETED, CANCELLED', CREATED_TS TIMESTAMP_NTZ, COMPLETED_TS TIMESTAMP_NTZ,
  DESCRIPTION VARCHAR, TECHNICIAN VARCHAR, PART_NUMBER VARCHAR, LABOR_HOURS NUMBER(6,2), COST_USD NUMBER(10,2),
  CREATED_BY VARCHAR COMMENT 'HUMAN or AI_AGENT');

-- Unstructured: technician inspection notes / thermal scans
CREATE OR REPLACE TABLE PDM_DB.RAW.INSPECTION_REPORTS (
  REPORT_ID VARCHAR PRIMARY KEY, MACHINE_ID VARCHAR, INSPECTION_DATE DATE,
  INSPECTION_TYPE VARCHAR COMMENT 'THERMAL_SCAN, VISUAL, ELECTRICAL', INSPECTOR VARCHAR, REPORT_TEXT VARCHAR);

-- Production for OEE
CREATE OR REPLACE TABLE PDM_DB.RAW.PRODUCTION_OUTPUT (
  MACHINE_ID VARCHAR, SHIFT_DATE DATE, SHIFT VARCHAR COMMENT 'A, B, C',
  PLANNED_MINUTES NUMBER, RUN_MINUTES NUMBER, TOTAL_UNITS NUMBER, GOOD_UNITS NUMBER);
