-- 05: CURATED layer (dynamic tables) + live-data simulator (procedure + task)
-- Re-runnable. Dynamic tables refresh themselves; downstream ones use TARGET_LAG = DOWNSTREAM.

USE WAREHOUSE COMPUTE_WH;

-- Machine sensors rolled up to the hour
CREATE OR REPLACE DYNAMIC TABLE PDM_DB.CURATED.SENSOR_HOURLY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH
  COMMENT = 'Hourly sensor aggregates per machine'
AS
SELECT MACHINE_ID,
       DATE_TRUNC('HOUR', READING_TS)            AS HOUR_TS,
       COUNT(*)                                  AS N_READINGS,
       AVG(VIBRATION_MM_S)                       AS VIBRATION_AVG,
       MAX(VIBRATION_MM_S)                       AS VIBRATION_MAX,
       AVG(BEARING_TEMP_C)                       AS BEARING_TEMP_AVG,
       MAX(BEARING_TEMP_C)                       AS BEARING_TEMP_MAX,
       AVG(MOTOR_WINDING_TEMP_C)                 AS WINDING_TEMP_AVG,
       MAX(MOTOR_WINDING_TEMP_C)                 AS WINDING_TEMP_MAX,
       AVG(RPM)                                  AS RPM_AVG,
       AVG(LOAD_PCT)                             AS LOAD_PCT_AVG,
       MAX(LOAD_PCT)                             AS LOAD_PCT_MAX,
       AVG((GREATEST(CURRENT_L1_A, CURRENT_L2_A, CURRENT_L3_A) - LEAST(CURRENT_L1_A, CURRENT_L2_A, CURRENT_L3_A))
           / NULLIF((CURRENT_L1_A + CURRENT_L2_A + CURRENT_L3_A) / 3, 0)) AS CURRENT_IMBALANCE_AVG,
       AVG(CABINET_HUMIDITY_PCT)                 AS HUMIDITY_AVG,
       MAX(CABINET_HUMIDITY_PCT)                 AS HUMIDITY_MAX,
       AVG(CABINET_TEMP_C)                       AS CABINET_TEMP_AVG,
       MIN(CABINET_TEMP_C - DEW_POINT_C)         AS DEW_MARGIN_MIN_C,
       MAX(IFF(LEAK_DETECTED, 1, 0))             AS LEAK_FLAG,
       MIN(INSULATION_RESISTANCE_MOHM)           AS INSULATION_MIN_MOHM,
       MAX(TERMINAL_TEMP_C)                      AS TERMINAL_TEMP_MAX,
       MAX(CONTACT_RESISTANCE_MOHM)              AS CONTACT_RES_MAX_MOHM,
       MAX(DC_RIPPLE_MV)                         AS DC_RIPPLE_MAX_MV
FROM PDM_DB.RAW.SENSOR_READINGS
GROUP BY MACHINE_ID, DATE_TRUNC('HOUR', READING_TS);

-- Power quality per feed per hour (readings + discrete events)
CREATE OR REPLACE DYNAMIC TABLE PDM_DB.CURATED.POWER_HOURLY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH
  COMMENT = 'Hourly power quality per power feed'
AS
SELECT POWER_FEED_ID,
       DATE_TRUNC('HOUR', READING_TS) AS HOUR_TS,
       AVG((VOLTAGE_L1_V + VOLTAGE_L2_V + VOLTAGE_L3_V) / 3) AS VOLTAGE_AVG,
       MAX((GREATEST(VOLTAGE_L1_V, VOLTAGE_L2_V, VOLTAGE_L3_V) - LEAST(VOLTAGE_L1_V, VOLTAGE_L2_V, VOLTAGE_L3_V))
           / NULLIF((VOLTAGE_L1_V + VOLTAGE_L2_V + VOLTAGE_L3_V) / 3, 0)) AS VOLTAGE_IMBALANCE_MAX,
       MAX(THD_PCT)            AS THD_MAX,
       MIN(FREQUENCY_HZ)       AS FREQ_MIN,
       MAX(FREQUENCY_HZ)       AS FREQ_MAX
FROM PDM_DB.RAW.POWER_READINGS
GROUP BY POWER_FEED_ID, DATE_TRUNC('HOUR', READING_TS);

CREATE OR REPLACE DYNAMIC TABLE PDM_DB.CURATED.POWER_EVENTS_HOURLY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH
  COMMENT = 'Power events per feed per hour, split by type'
AS
SELECT POWER_FEED_ID,
       DATE_TRUNC('HOUR', EVENT_TS) AS HOUR_TS,
       COUNT(*)                                                        AS N_EVENTS,
       COUNT_IF(EVENT_TYPE = 'OUTAGE')                                 AS N_OUTAGE,
       COUNT_IF(EVENT_TYPE IN ('SURGE', 'TRANSIENT_SPIKE'))            AS N_SPIKE,
       COUNT_IF(EVENT_TYPE IN ('SURGE', 'TRANSIENT_SPIKE') AND NOT SURGE_PROTECTOR_TRIGGERED) AS N_UNPROTECTED_SPIKE,
       COUNT_IF(EVENT_TYPE = 'RESTART_INRUSH')                         AS N_INRUSH,
       COUNT_IF(EVENT_TYPE = 'SAG')                                    AS N_SAG
FROM PDM_DB.RAW.POWER_EVENTS
GROUP BY POWER_FEED_ID, DATE_TRUNC('HOUR', EVENT_TS);

-- Controller / edge PC load per machine per hour
CREATE OR REPLACE DYNAMIC TABLE PDM_DB.CURATED.SYSTEM_HOURLY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH
  COMMENT = 'Hourly controller / HMI / edge PC load per machine (max across devices)'
AS
SELECT MACHINE_ID,
       DATE_TRUNC('HOUR', READING_TS) AS HOUR_TS,
       MAX(CPU_PCT)         AS CPU_MAX,
       MAX(MEMORY_PCT)      AS MEMORY_MAX,
       MAX(DISK_PCT)        AS DISK_MAX,
       SUM(NETWORK_ERRORS)  AS NETWORK_ERRORS,
       SUM(WATCHDOG_RESETS) AS WATCHDOG_RESETS
FROM PDM_DB.RAW.SYSTEM_METRICS
GROUP BY MACHINE_ID, DATE_TRUNC('HOUR', READING_TS);

CREATE OR REPLACE DYNAMIC TABLE PDM_DB.CURATED.FAULTS_HOURLY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH
  COMMENT = 'Controller / drive fault counts per machine per hour'
AS
SELECT MACHINE_ID,
       DATE_TRUNC('HOUR', FAULT_TS) AS HOUR_TS,
       COUNT(*)                                       AS N_FAULTS,
       COUNT_IF(SEVERITY IN ('HIGH', 'CRITICAL'))     AS N_SEVERE_FAULTS,
       COUNT_IF(SOURCE = 'DRIVE')                     AS N_DRIVE_FAULTS,
       COUNT_IF(SOURCE = 'PSU')                       AS N_PSU_FAULTS
FROM PDM_DB.RAW.FAULT_LOGS
GROUP BY MACHINE_ID, DATE_TRUNC('HOUR', FAULT_TS);

-- Model-ready hourly features: one row per machine-hour, OT + power + controller + asset context
CREATE OR REPLACE DYNAMIC TABLE PDM_DB.CURATED.MACHINE_FEATURES_HOURLY
  TARGET_LAG = '15 minutes' WAREHOUSE = COMPUTE_WH
  COMMENT = 'Hourly feature row per machine. Input for the failure model. No ground-truth columns.'
AS
SELECT s.MACHINE_ID, s.HOUR_TS,
       m.LINE_ID, l.PLANT_ID, l.POWER_FEED_ID, m.MACHINE_TYPE, m.CRITICALITY,
       l.HAS_UPS, l.HAS_SURGE_PROTECTION, p.CLIMATE_ZONE,
       s.N_READINGS, s.VIBRATION_AVG, s.VIBRATION_MAX, s.BEARING_TEMP_AVG, s.BEARING_TEMP_MAX,
       s.WINDING_TEMP_AVG, s.WINDING_TEMP_MAX, s.RPM_AVG, s.RPM_AVG / NULLIF(m.RATED_RPM, 0) AS RPM_RATIO,
       s.LOAD_PCT_AVG, s.LOAD_PCT_MAX, s.CURRENT_IMBALANCE_AVG,
       s.HUMIDITY_AVG, s.HUMIDITY_MAX, s.CABINET_TEMP_AVG, s.DEW_MARGIN_MIN_C, s.LEAK_FLAG,
       s.INSULATION_MIN_MOHM, s.TERMINAL_TEMP_MAX, s.CONTACT_RES_MAX_MOHM, s.DC_RIPPLE_MAX_MV,
       pw.VOLTAGE_AVG, pw.VOLTAGE_IMBALANCE_MAX, pw.THD_MAX,
       COALESCE(pe.N_EVENTS, 0) AS POWER_EVENTS, COALESCE(pe.N_OUTAGE, 0) AS POWER_OUTAGES,
       COALESCE(pe.N_SPIKE, 0) AS POWER_SPIKES, COALESCE(pe.N_UNPROTECTED_SPIKE, 0) AS UNPROTECTED_SPIKES,
       COALESCE(pe.N_INRUSH, 0) AS RESTART_INRUSH,
       sy.CPU_MAX, sy.MEMORY_MAX, sy.DISK_MAX, sy.NETWORK_ERRORS, sy.WATCHDOG_RESETS,
       COALESCE(f.N_FAULTS, 0) AS FAULTS, COALESCE(f.N_SEVERE_FAULTS, 0) AS SEVERE_FAULTS,
       COALESCE(f.N_DRIVE_FAULTS, 0) AS DRIVE_FAULTS, COALESCE(f.N_PSU_FAULTS, 0) AS PSU_FAULTS
FROM PDM_DB.CURATED.SENSOR_HOURLY s
JOIN PDM_DB.RAW.MACHINES m          ON m.MACHINE_ID = s.MACHINE_ID
JOIN PDM_DB.RAW.PRODUCTION_LINES l  ON l.LINE_ID = m.LINE_ID
JOIN PDM_DB.RAW.PLANTS p            ON p.PLANT_ID = l.PLANT_ID
LEFT JOIN PDM_DB.CURATED.POWER_HOURLY pw        ON pw.POWER_FEED_ID = l.POWER_FEED_ID AND pw.HOUR_TS = s.HOUR_TS
LEFT JOIN PDM_DB.CURATED.POWER_EVENTS_HOURLY pe ON pe.POWER_FEED_ID = l.POWER_FEED_ID AND pe.HOUR_TS = s.HOUR_TS
LEFT JOIN PDM_DB.CURATED.SYSTEM_HOURLY sy       ON sy.MACHINE_ID = s.MACHINE_ID AND sy.HOUR_TS = s.HOUR_TS
LEFT JOIN PDM_DB.CURATED.FAULTS_HOURLY f        ON f.MACHINE_ID = s.MACHINE_ID AND f.HOUR_TS = s.HOUR_TS;

-- Daily OEE per machine (sum of shifts) with availability / performance / quality
CREATE OR REPLACE DYNAMIC TABLE PDM_DB.CURATED.OEE_DAILY
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
  COMMENT = 'Daily OEE per machine = availability * performance * quality'
AS
SELECT o.MACHINE_ID, m.LINE_ID, l.PLANT_ID, o.SHIFT_DATE,
       SUM(o.PLANNED_MINUTES) AS PLANNED_MINUTES, SUM(o.RUN_MINUTES) AS RUN_MINUTES,
       SUM(o.TOTAL_UNITS) AS TOTAL_UNITS, SUM(o.GOOD_UNITS) AS GOOD_UNITS,
       SUM(o.RUN_MINUTES) / NULLIF(SUM(o.PLANNED_MINUTES), 0)                              AS AVAILABILITY,
       LEAST(1, SUM(o.TOTAL_UNITS) * MAX(m.IDEAL_CYCLE_TIME_SEC) / NULLIF(SUM(o.RUN_MINUTES) * 60, 0)) AS PERFORMANCE,
       SUM(o.GOOD_UNITS) / NULLIF(SUM(o.TOTAL_UNITS), 0)                                   AS QUALITY,
       PDM_DB.APP.OEE(SUM(o.PLANNED_MINUTES), SUM(o.RUN_MINUTES), SUM(o.TOTAL_UNITS), SUM(o.GOOD_UNITS),
                      MAX(m.IDEAL_CYCLE_TIME_SEC))                                         AS OEE
FROM PDM_DB.RAW.PRODUCTION_OUTPUT o
JOIN PDM_DB.RAW.MACHINES m         ON m.MACHINE_ID = o.MACHINE_ID
JOIN PDM_DB.RAW.PRODUCTION_LINES l ON l.LINE_ID = m.LINE_ID
GROUP BY o.MACHINE_ID, m.LINE_ID, l.PLANT_ID, o.SHIFT_DATE;

-- Current status of every redundant component and whether its group still has a backup
CREATE OR REPLACE DYNAMIC TABLE PDM_DB.CURATED.REDUNDANCY_STATUS
  TARGET_LAG = '15 minutes' WAREHOUSE = COMPUTE_WH
  COMMENT = 'Latest status per redundant component; NO_BACKUP when only one healthy member is left'
AS
WITH latest AS (
  SELECT COMPONENT_ID, STATUS, DETAIL, STATUS_TS
  FROM PDM_DB.RAW.COMPONENT_HEALTH
  QUALIFY ROW_NUMBER() OVER (PARTITION BY COMPONENT_ID ORDER BY STATUS_TS DESC) = 1
), comp AS (
  SELECT c.COMPONENT_ID, c.MACHINE_ID, c.COMPONENT_TYPE, c.REDUNDANCY_GROUP, c.PART_NUMBER,
         COALESCE(lt.STATUS, 'HEALTHY') AS STATUS, lt.DETAIL, lt.STATUS_TS
  FROM PDM_DB.RAW.COMPONENTS c
  LEFT JOIN latest lt ON lt.COMPONENT_ID = c.COMPONENT_ID
  WHERE c.REDUNDANCY_GROUP IS NOT NULL
)
SELECT comp.*,
       COUNT(*) OVER (PARTITION BY MACHINE_ID, REDUNDANCY_GROUP)                    AS GROUP_SIZE,
       COUNT_IF(STATUS = 'HEALTHY') OVER (PARTITION BY MACHINE_ID, REDUNDANCY_GROUP) AS GROUP_HEALTHY,
       CASE WHEN COUNT_IF(STATUS = 'HEALTHY') OVER (PARTITION BY MACHINE_ID, REDUNDANCY_GROUP) = 0 THEN 'DOWN'
            WHEN COUNT_IF(STATUS = 'HEALTHY') OVER (PARTITION BY MACHINE_ID, REDUNDANCY_GROUP) = 1
                 AND COUNT(*) OVER (PARTITION BY MACHINE_ID, REDUNDANCY_GROUP) > 1 THEN 'NO_BACKUP'
            WHEN COUNT_IF(STATUS <> 'HEALTHY') OVER (PARTITION BY MACHINE_ID, REDUNDANCY_GROUP) > 0 THEN 'DEGRADED'
            ELSE 'OK' END AS GROUP_STATE
FROM comp;

-- Live data simulator: appends the next 5-minute reading per machine / feed, drifting from the last value.
CREATE OR REPLACE PROCEDURE PDM_DB.APP.SIMULATE_LIVE_READINGS()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Append one new 5-minute sensor + power reading per machine/feed (demo live feed)'
EXECUTE AS OWNER
AS
$$
DECLARE
  n INTEGER;
BEGIN
  INSERT INTO PDM_DB.RAW.SENSOR_READINGS
  SELECT MACHINE_ID, DATEADD('MINUTE', 5, READING_TS),
         GREATEST(0, VIBRATION_MM_S * UNIFORM(0.97, 1.03, RANDOM())),
         BEARING_TEMP_C + UNIFORM(-0.3, 0.3, RANDOM()),
         MOTOR_WINDING_TEMP_C + UNIFORM(-0.3, 0.3, RANDOM()),
         RPM * UNIFORM(0.995, 1.005, RANDOM()),
         CURRENT_L1_A * UNIFORM(0.99, 1.01, RANDOM()),
         CURRENT_L2_A * UNIFORM(0.99, 1.01, RANDOM()),
         CURRENT_L3_A * UNIFORM(0.99, 1.01, RANDOM()),
         LEAST(100, GREATEST(0, LOAD_PCT + UNIFORM(-1.0, 1.0, RANDOM()))),
         LEAST(100, GREATEST(1, CABINET_HUMIDITY_PCT + UNIFORM(-0.5, 0.5, RANDOM()))),
         CABINET_TEMP_C + UNIFORM(-0.2, 0.2, RANDOM()),
         DEW_POINT_C, LEAK_DETECTED, INSULATION_RESISTANCE_MOHM, TERMINAL_TEMP_C,
         CONTACT_RESISTANCE_MOHM, DC_RIPPLE_MV
  FROM PDM_DB.RAW.SENSOR_READINGS
  QUALIFY ROW_NUMBER() OVER (PARTITION BY MACHINE_ID ORDER BY READING_TS DESC) = 1;
  n := SQLROWCOUNT;

  -- keep dew point consistent with the new temperature / humidity
  UPDATE PDM_DB.RAW.SENSOR_READINGS s
     SET DEW_POINT_C = PDM_DB.APP.DEW_POINT(CABINET_TEMP_C, CABINET_HUMIDITY_PCT)
   WHERE READING_TS = (SELECT MAX(READING_TS) FROM PDM_DB.RAW.SENSOR_READINGS);

  INSERT INTO PDM_DB.RAW.POWER_READINGS
  SELECT POWER_FEED_ID, DATEADD('MINUTE', 5, READING_TS),
         VOLTAGE_L1_V + UNIFORM(-1.0, 1.0, RANDOM()), VOLTAGE_L2_V + UNIFORM(-1.0, 1.0, RANDOM()),
         VOLTAGE_L3_V + UNIFORM(-1.0, 1.0, RANDOM()), 50 + UNIFORM(-0.05, 0.05, RANDOM()),
         GREATEST(0, THD_PCT + UNIFORM(-0.2, 0.2, RANDOM()))
  FROM PDM_DB.RAW.POWER_READINGS
  QUALIFY ROW_NUMBER() OVER (PARTITION BY POWER_FEED_ID ORDER BY READING_TS DESC) = 1;

  RETURN 'LIVE OK: ' || n || ' machine readings appended';
END;
$$;

-- Created SUSPENDED to avoid surprise credit use. Start with: ALTER TASK PDM_DB.APP.LIVE_FEED_TASK RESUME;
CREATE OR REPLACE TASK PDM_DB.APP.LIVE_FEED_TASK
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '5 MINUTE'
  COMMENT = 'Demo live feed: appends new sensor/power readings every 5 minutes'
AS CALL PDM_DB.APP.SIMULATE_LIVE_READINGS();
