-- 06: failure prediction model + ALERTS
-- Labels come from RAW.FAILURES only. ML.SYNTH_GROUND_TRUTH is never used here (evaluation only, see 07).

USE WAREHOUSE COMPUTE_WH;

-- Hourly features + short-term trends (rows are one per machine-hour, so ROWS windows = hours)
CREATE OR REPLACE VIEW PDM_DB.ML.FEATURES_V
  COMMENT = 'Model input: hourly machine features with 24h / 7d trend features'
AS
SELECT f.*,
  AVG(VIBRATION_AVG)      OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  AS VIBRATION_24H,
  AVG(VIBRATION_AVG)      OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 167 PRECEDING AND CURRENT ROW)  AS VIBRATION_7D,
  VIBRATION_24H / NULLIF(VIBRATION_7D, 0)                          AS VIBRATION_TREND,
  AVG(BEARING_TEMP_AVG)   OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  - AVG(BEARING_TEMP_AVG) OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 167 PRECEDING AND CURRENT ROW) AS BEARING_TEMP_TREND,
  AVG(WINDING_TEMP_AVG)   OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  - AVG(WINDING_TEMP_AVG) OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 167 PRECEDING AND CURRENT ROW) AS WINDING_TEMP_TREND,
  AVG(LOAD_PCT_AVG)       OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  AS LOAD_24H,
  AVG(HUMIDITY_AVG)       OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  AS HUMIDITY_24H,
  MIN(DEW_MARGIN_MIN_C)   OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  AS DEW_MARGIN_24H,
  MAX(LEAK_FLAG)          OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  AS LEAK_24H,
  MIN(INSULATION_MIN_MOHM) OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS INSULATION_24H,
  MIN(INSULATION_MIN_MOHM) OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) - MIN(INSULATION_MIN_MOHM) OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 167 PRECEDING AND CURRENT ROW) AS INSULATION_TREND,
  MAX(TERMINAL_TEMP_MAX)  OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  - AVG(TERMINAL_TEMP_MAX) OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 167 PRECEDING AND CURRENT ROW)   AS TERMINAL_TEMP_TREND,
  MAX(CONTACT_RES_MAX_MOHM) OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS CONTACT_RES_24H,
  MAX(VOLTAGE_IMBALANCE_MAX) OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS VOLTAGE_IMBALANCE_24H,
  MAX(THD_MAX)            OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  AS THD_24H,
  SUM(UNPROTECTED_SPIKES) OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW)  AS UNPROTECTED_SPIKES_72H,
  SUM(POWER_OUTAGES)      OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW)  AS OUTAGES_72H,
  SUM(RESTART_INRUSH)     OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 71 PRECEDING AND CURRENT ROW)  AS INRUSH_72H,
  MAX(MEMORY_MAX)         OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  AS MEMORY_24H,
  MAX(DISK_MAX)           OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  AS DISK_24H,
  SUM(WATCHDOG_RESETS)    OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  AS WATCHDOG_24H,
  SUM(FAULTS)             OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  AS FAULTS_24H,
  SUM(PSU_FAULTS)         OVER (PARTITION BY f.MACHINE_ID ORDER BY f.HOUR_TS ROWS BETWEEN 23 PRECEDING AND CURRENT ROW)  AS PSU_FAULTS_24H
FROM PDM_DB.CURATED.MACHINE_FEATURES_HOURLY f;

-- Label = mode of the next failure within 48h, else NONE. Hours while the machine is down are excluded.
CREATE OR REPLACE TABLE PDM_DB.ML.TRAINING_DATA
  COMMENT = 'Features + LABEL (failure mode within next 48h or NONE). Built from RAW.FAILURES.'
AS
WITH lab AS (
  SELECT f.MACHINE_ID, f.HOUR_TS,
         MIN_BY(x.FAILURE_MODE, IFF(x.FAILURE_TS > f.HOUR_TS, x.FAILURE_TS, NULL)) AS NEXT_MODE,
         MAX(IFF(f.HOUR_TS >= DATE_TRUNC('HOUR', x.FAILURE_TS)
                 AND f.HOUR_TS < COALESCE(x.RESTORED_TS, DATEADD('DAY', 1, x.FAILURE_TS)), 1, 0)) AS IS_DOWN
  FROM PDM_DB.CURATED.MACHINE_FEATURES_HOURLY f
  JOIN PDM_DB.RAW.FAILURES x
    ON x.MACHINE_ID = f.MACHINE_ID
   AND x.FAILURE_TS > DATEADD('DAY', -3, f.HOUR_TS) AND x.FAILURE_TS <= DATEADD('HOUR', 48, f.HOUR_TS)
  GROUP BY f.MACHINE_ID, f.HOUR_TS
)
SELECT f.*, COALESCE(l.NEXT_MODE, 'NONE') AS LABEL
FROM PDM_DB.ML.FEATURES_V f
LEFT JOIN lab l ON l.MACHINE_ID = f.MACHINE_ID AND l.HOUR_TS = f.HOUR_TS
WHERE COALESCE(l.IS_DOWN, 0) = 0;

-- Training input: drop identifiers and timestamps so the model learns from signals only
CREATE OR REPLACE VIEW PDM_DB.ML.TRAIN_V AS
SELECT * EXCLUDE (MACHINE_ID, HOUR_TS, LINE_ID, PLANT_ID, POWER_FEED_ID)
FROM PDM_DB.ML.TRAINING_DATA WHERE HOUR_TS < '2026-09-15';

CREATE OR REPLACE VIEW PDM_DB.ML.TEST_V AS
SELECT * FROM PDM_DB.ML.TRAINING_DATA WHERE HOUR_TS >= '2026-09-15';

CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION PDM_DB.ML.FAILURE_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'PDM_DB.ML.TRAIN_V'),
  TARGET_COLNAME => 'LABEL',
  CONFIG_OBJECT => {'evaluate': TRUE, 'on_error': 'skip'});

-- Scored predictions (appended each run)
CREATE TABLE IF NOT EXISTS PDM_DB.ML.PREDICTIONS (
  MACHINE_ID VARCHAR, HOUR_TS TIMESTAMP_NTZ, SCORED_AT TIMESTAMP_NTZ,
  PREDICTED_MODE VARCHAR, FAILURE_RISK FLOAT, TOP_MODE VARCHAR, TOP_MODE_PROB FLOAT, PROBABILITIES VARIANT);

-- Alerts consumed by the agent and the Streamlit app
CREATE TABLE IF NOT EXISTS PDM_DB.APP.ALERTS (
  ALERT_ID VARCHAR DEFAULT UUID_STRING(), CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
  MACHINE_ID VARCHAR, COMPONENT_ID VARCHAR,
  ALERT_TYPE VARCHAR COMMENT 'FAILURE_RISK, NO_BACKUP, SPARE_STOCKOUT',
  PREDICTED_MODE VARCHAR, RISK_SCORE FLOAT, SEVERITY VARCHAR COMMENT 'CRITICAL, HIGH, MEDIUM',
  MESSAGE VARCHAR, STATUS VARCHAR DEFAULT 'OPEN' COMMENT 'OPEN, ACKNOWLEDGED, CLOSED', DATA_TS TIMESTAMP_NTZ);

-- Scores the latest hour per machine and refreshes OPEN alerts (closes ones that no longer apply)
CREATE OR REPLACE PROCEDURE PDM_DB.APP.REFRESH_ALERTS(RISK_THRESHOLD FLOAT DEFAULT 0.5)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Score latest machine-hour with FAILURE_MODEL, write ML.PREDICTIONS and refresh APP.ALERTS'
EXECUTE AS OWNER
AS
$$
DECLARE
  n_risk INTEGER;
  n_other INTEGER;
BEGIN
  INSERT INTO PDM_DB.ML.PREDICTIONS
  WITH latest AS (
    SELECT * FROM PDM_DB.ML.FEATURES_V QUALIFY ROW_NUMBER() OVER (PARTITION BY MACHINE_ID ORDER BY HOUR_TS DESC) = 1
  ), scored AS (
    SELECT MACHINE_ID, HOUR_TS,
           PDM_DB.ML.FAILURE_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(* EXCLUDE (MACHINE_ID, HOUR_TS, LINE_ID, PLANT_ID, POWER_FEED_ID))) AS P
    FROM latest
  ), modes AS (
    SELECT MACHINE_ID, HOUR_TS, P, k.KEY AS MODE, k.VALUE::FLOAT AS PROB
    FROM scored, LATERAL FLATTEN(INPUT => P:probability) k WHERE k.KEY <> 'NONE'
  )
  SELECT MACHINE_ID, HOUR_TS, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
         ANY_VALUE(P:class::STRING), 1 - COALESCE(ANY_VALUE(P:probability:NONE::FLOAT), 0),
         MAX_BY(MODE, PROB), MAX(PROB), ANY_VALUE(P:probability)
  FROM modes GROUP BY MACHINE_ID, HOUR_TS;

  -- close alerts from earlier runs; current state is re-raised below
  UPDATE PDM_DB.APP.ALERTS SET STATUS = 'CLOSED' WHERE STATUS = 'OPEN';

  INSERT INTO PDM_DB.APP.ALERTS (MACHINE_ID, ALERT_TYPE, PREDICTED_MODE, RISK_SCORE, SEVERITY, MESSAGE, DATA_TS)
  SELECT p.MACHINE_ID, 'FAILURE_RISK', p.TOP_MODE, ROUND(p.FAILURE_RISK, 3),
         CASE WHEN p.FAILURE_RISK >= 0.8 OR m.CRITICALITY = 'A' THEN 'CRITICAL'
              WHEN p.FAILURE_RISK >= 0.65 THEN 'HIGH' ELSE 'MEDIUM' END,
         m.MACHINE_NAME || ': ' || ROUND(p.FAILURE_RISK * 100) || '% risk of ' || p.TOP_MODE || ' failure in the next 48h',
         p.HOUR_TS
  FROM PDM_DB.ML.PREDICTIONS p JOIN PDM_DB.RAW.MACHINES m ON m.MACHINE_ID = p.MACHINE_ID
  WHERE p.SCORED_AT = (SELECT MAX(SCORED_AT) FROM PDM_DB.ML.PREDICTIONS) AND p.FAILURE_RISK >= :RISK_THRESHOLD;
  n_risk := SQLROWCOUNT;

  INSERT INTO PDM_DB.APP.ALERTS (MACHINE_ID, COMPONENT_ID, ALERT_TYPE, PREDICTED_MODE, RISK_SCORE, SEVERITY, MESSAGE, DATA_TS)
  SELECT r.MACHINE_ID, r.COMPONENT_ID, 'NO_BACKUP', 'REDUNDANCY_LOSS', NULL,
         IFF(r.GROUP_STATE = 'DOWN', 'CRITICAL', 'HIGH'),
         r.MACHINE_ID || ' ' || r.REDUNDANCY_GROUP || ' is ' || r.GROUP_STATE || ': ' || r.COMPONENT_ID || ' ' || r.STATUS
           || COALESCE(' (' || r.DETAIL || ')', '') || '. Spares at plant: ' || COALESCE(sp.QTY_ON_HAND, 0),
         r.STATUS_TS
  FROM PDM_DB.CURATED.REDUNDANCY_STATUS r
  JOIN PDM_DB.RAW.MACHINES m ON m.MACHINE_ID = r.MACHINE_ID
  JOIN PDM_DB.RAW.PRODUCTION_LINES l ON l.LINE_ID = m.LINE_ID
  LEFT JOIN PDM_DB.RAW.SPARE_PARTS sp ON sp.PART_NUMBER = r.PART_NUMBER AND sp.PLANT_ID = l.PLANT_ID
  WHERE r.GROUP_STATE IN ('NO_BACKUP', 'DOWN') AND r.STATUS <> 'HEALTHY';

  -- spare parts at or below reorder point where an alerted machine needs that part type
  INSERT INTO PDM_DB.APP.ALERTS (MACHINE_ID, ALERT_TYPE, SEVERITY, MESSAGE, DATA_TS)
  SELECT NULL, 'SPARE_STOCKOUT', IFF(QTY_ON_HAND = 0, 'HIGH', 'MEDIUM'),
         'Plant ' || PLANT_ID || ': ' || PART_NAME || ' (' || PART_NUMBER || ') on hand ' || QTY_ON_HAND
           || ', reorder point ' || REORDER_POINT || ', lead time ' || LEAD_TIME_DAYS || ' days',
         CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
  FROM PDM_DB.RAW.SPARE_PARTS sp
  WHERE QTY_ON_HAND <= REORDER_POINT
    AND EXISTS (SELECT 1 FROM PDM_DB.APP.ALERTS a
                JOIN PDM_DB.RAW.MACHINES m ON m.MACHINE_ID = a.MACHINE_ID
                JOIN PDM_DB.RAW.PRODUCTION_LINES l ON l.LINE_ID = m.LINE_ID
                JOIN PDM_DB.RAW.COMPONENTS c ON c.MACHINE_ID = a.MACHINE_ID
                WHERE a.STATUS = 'OPEN' AND l.PLANT_ID = sp.PLANT_ID AND c.PART_NUMBER = sp.PART_NUMBER);
  n_other := SQLROWCOUNT;

  RETURN 'ALERTS OK: ' || n_risk || ' failure-risk alerts, ' || n_other || ' stockout alerts';
END;
$$;

-- Hourly scoring. Created SUSPENDED; start with: ALTER TASK PDM_DB.APP.ALERTS_TASK RESUME;
CREATE OR REPLACE TASK PDM_DB.APP.ALERTS_TASK
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 5 * * * * UTC'
  COMMENT = 'Hourly: score machines and refresh APP.ALERTS'
AS CALL PDM_DB.APP.REFRESH_ALERTS();
